export const SUN = {
	name: "sun",
	displayName: "Sun",
	displayNameId: "Matahari",
	texturePath: "/textures/sun.jpg",
	size: 6,
	axialTilt: 7.25,
};

export const PLANETS = [
	{
		name: "mercury",
		displayName: "Mercury",
		displayNameId: "Merkurius",
		texturePath: "/textures/mercury.jpg",
		size: 0.38,
		orbitalRadius: 12,
		orbitalSpeed: 1.8,
		axialTilt: 0.03,
	},
	{
		name: "venus",
		displayName: "Venus",
		displayNameId: "Venus",
		texturePath: "/textures/venus.jpg",
		size: 0.95,
		orbitalRadius: 16,
		orbitalSpeed: 1.25,
		axialTilt: 177.4,
	},
	{
		name: "earth",
		displayName: "Earth",
		displayNameId: "Bumi",
		texturePath: "/textures/earth.jpg",
		size: 1.0,
		orbitalRadius: 21,
		orbitalSpeed: 1.0,
		axialTilt: 23.44,
	},
	{
		name: "mars",
		displayName: "Mars",
		displayNameId: "Mars",
		texturePath: "/textures/mars.jpg",
		size: 0.53,
		orbitalRadius: 28,
		orbitalSpeed: 0.78,
		axialTilt: 25.19,
	},
	{
		name: "jupiter",
		displayName: "Jupiter",
		displayNameId: "Jupiter",
		texturePath: "/textures/jupiter.jpg",
		size: 2.5,
		orbitalRadius: 44,
		orbitalSpeed: 0.42,
		axialTilt: 3.13,
	},
	{
		name: "saturn",
		displayName: "Saturn",
		displayNameId: "Saturnus",
		texturePath: "/textures/saturn.jpg",
		size: 2.2,
		orbitalRadius: 60,
		orbitalSpeed: 0.3,
		hasRing: true,
		ringTexturePath: "/textures/saturn_ring.png",
		axialTilt: 26.73,
	},
	{
		name: "uranus",
		displayName: "Uranus",
		displayNameId: "Uranus",
		texturePath: "/textures/uranus.jpg",
		size: 1.5,
		orbitalRadius: 74,
		orbitalSpeed: 0.2,
		axialTilt: 97.77,
	},
	{
		name: "neptune",
		displayName: "Neptune",
		displayNameId: "Neptunus",
		texturePath: "/textures/neptune.jpg",
		size: 1.45,
		orbitalRadius: 86,
		orbitalSpeed: 0.16,
		axialTilt: 28.32,
	},
];
